# Generated by Django 2.2.1 on 2019-06-01 22:49

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('publisher', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_type', models.CharField(default=web.models.QuestionType((1,)), max_length=1)),
                ('category', models.TextField(default='general')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.IntegerField(default=web.models.ChoiceType((1,)))),
                ('value', models.TextField()),
                ('weight', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Question')),
            ],
        ),
    ]
