# Generated by Django 2.2.1 on 2019-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('question_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_id', 'question_id')},
            },
        ),
    ]
