# Generated by Django 2.2.1 on 2019-06-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_answer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=100)),
                ('question_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user_name',
        ),
    ]
