# Generated by Django 2.2.1 on 2019-06-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190618_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.IntegerField(choices=[(1, 'Selectable'), (2, 'Fillable')], default=1),
        ),
    ]
